# Generated by Django 5.0.4 on 2024-05-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CachedResponse",
            fields=[
                (
                    "request_md5",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed_at", models.DateTimeField(auto_now=True)),
                ("request_ip", models.GenericIPAddressField(db_index=True)),
                ("request_method", models.CharField(max_length=16)),
                (
                    "request_host",
                    models.CharField(db_index=True, max_length=500, null=True),
                ),
                ("request_path", models.CharField(max_length=200)),
                ("request_headers", models.JSONField()),
                ("request_body", models.TextField()),
                ("response_status_code", models.PositiveSmallIntegerField()),
                ("response_headers", models.JSONField()),
                ("response_body", models.TextField()),
                ("response_content_type", models.CharField(max_length=200)),
                ("response_time", models.DurationField()),
            ],
        ),
    ]
